#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: E:/study workspace(springboot)/sellLog/sell.log
#  level: debug
##  level: com.gyz.leiming:debug
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.105/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    配置全局参数，如果是null不返回
#  jackson:
#    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell
#      spring.jpa.properties.hibernate.format_sql=true